name: GitHub-Profile-3D-Contrib

on:
  schedule: # Runs daily at 18:00 UTC (03:30 IST)
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push Changes
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${REPO}.git
          git add -A .
          git commit -m "generated" || echo "No changes to commit"
          git push origin HEAD:main
